// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type AirState byte

const (
	/// All wheels are on the ground
	AirStateOnGround      AirState = 0
	/// When the bot is jumping,
	/// then InAir right after
	AirStateJumping       AirState = 1
	/// When the bot is double jumping,
	/// then InAir right after
	AirStateDoubleJumping AirState = 2
	/// When the bot is dodging,
	/// then InAir right after
	AirStateDodging       AirState = 3
	AirStateInAir         AirState = 4
)

var EnumNamesAirState = map[AirState]string{
	AirStateOnGround:      "OnGround",
	AirStateJumping:       "Jumping",
	AirStateDoubleJumping: "DoubleJumping",
	AirStateDodging:       "Dodging",
	AirStateInAir:         "InAir",
}

var EnumValuesAirState = map[string]AirState{
	"OnGround":      AirStateOnGround,
	"Jumping":       AirStateJumping,
	"DoubleJumping": AirStateDoubleJumping,
	"Dodging":       AirStateDodging,
	"InAir":         AirStateInAir,
}

func (v AirState) String() string {
	if s, ok := EnumNamesAirState[v]; ok {
		return s
	}
	return "AirState(" + strconv.FormatInt(int64(v), 10) + ")"
}
