// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BallWeightOption byte

const (
	BallWeightOptionDefault     BallWeightOption = 0
	BallWeightOptionLight       BallWeightOption = 1
	BallWeightOptionHeavy       BallWeightOption = 2
	BallWeightOptionSuper_Light BallWeightOption = 3
)

var EnumNamesBallWeightOption = map[BallWeightOption]string{
	BallWeightOptionDefault:     "Default",
	BallWeightOptionLight:       "Light",
	BallWeightOptionHeavy:       "Heavy",
	BallWeightOptionSuper_Light: "Super_Light",
}

var EnumValuesBallWeightOption = map[string]BallWeightOption{
	"Default":     BallWeightOptionDefault,
	"Light":       BallWeightOptionLight,
	"Heavy":       BallWeightOptionHeavy,
	"Super_Light": BallWeightOptionSuper_Light,
}

func (v BallWeightOption) String() string {
	if s, ok := EnumNamesBallWeightOption[v]; ok {
		return s
	}
	return "BallWeightOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
