// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BallTypeOption byte

const (
	BallTypeOptionDefault     BallTypeOption = 0
	BallTypeOptionCube        BallTypeOption = 1
	BallTypeOptionPuck        BallTypeOption = 2
	BallTypeOptionBasketball  BallTypeOption = 3
	BallTypeOptionBeachball   BallTypeOption = 4
	BallTypeOptionAnniversary BallTypeOption = 5
	BallTypeOptionHaunted     BallTypeOption = 6
	BallTypeOptionEkin        BallTypeOption = 7
	BallTypeOptionSpookyCube  BallTypeOption = 8
)

var EnumNamesBallTypeOption = map[BallTypeOption]string{
	BallTypeOptionDefault:     "Default",
	BallTypeOptionCube:        "Cube",
	BallTypeOptionPuck:        "Puck",
	BallTypeOptionBasketball:  "Basketball",
	BallTypeOptionBeachball:   "Beachball",
	BallTypeOptionAnniversary: "Anniversary",
	BallTypeOptionHaunted:     "Haunted",
	BallTypeOptionEkin:        "Ekin",
	BallTypeOptionSpookyCube:  "SpookyCube",
}

var EnumValuesBallTypeOption = map[string]BallTypeOption{
	"Default":     BallTypeOptionDefault,
	"Cube":        BallTypeOptionCube,
	"Puck":        BallTypeOptionPuck,
	"Basketball":  BallTypeOptionBasketball,
	"Beachball":   BallTypeOptionBeachball,
	"Anniversary": BallTypeOptionAnniversary,
	"Haunted":     BallTypeOptionHaunted,
	"Ekin":        BallTypeOptionEkin,
	"SpookyCube":  BallTypeOptionSpookyCube,
}

func (v BallTypeOption) String() string {
	if s, ok := EnumNamesBallTypeOption[v]; ok {
		return s
	}
	return "BallTypeOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
