// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BallSizeOption byte

const (
	BallSizeOptionDefault  BallSizeOption = 0
	BallSizeOptionSmall    BallSizeOption = 1
	BallSizeOptionMedium   BallSizeOption = 2
	BallSizeOptionLarge    BallSizeOption = 3
	BallSizeOptionGigantic BallSizeOption = 4
)

var EnumNamesBallSizeOption = map[BallSizeOption]string{
	BallSizeOptionDefault:  "Default",
	BallSizeOptionSmall:    "Small",
	BallSizeOptionMedium:   "Medium",
	BallSizeOptionLarge:    "Large",
	BallSizeOptionGigantic: "Gigantic",
}

var EnumValuesBallSizeOption = map[string]BallSizeOption{
	"Default":  BallSizeOptionDefault,
	"Small":    BallSizeOptionSmall,
	"Medium":   BallSizeOptionMedium,
	"Large":    BallSizeOptionLarge,
	"Gigantic": BallSizeOptionGigantic,
}

func (v BallSizeOption) String() string {
	if s, ok := EnumNamesBallSizeOption[v]; ok {
		return s
	}
	return "BallSizeOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
