// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BallTypeOption byte

const (
	BallTypeOptionDefault    BallTypeOption = 0
	BallTypeOptionCube       BallTypeOption = 1
	BallTypeOptionPuck       BallTypeOption = 2
	BallTypeOptionBasketball BallTypeOption = 3
)

var EnumNamesBallTypeOption = map[BallTypeOption]string{
	BallTypeOptionDefault:    "Default",
	BallTypeOptionCube:       "Cube",
	BallTypeOptionPuck:       "Puck",
	BallTypeOptionBasketball: "Basketball",
}

var EnumValuesBallTypeOption = map[string]BallTypeOption{
	"Default":    BallTypeOptionDefault,
	"Cube":       BallTypeOptionCube,
	"Puck":       BallTypeOptionPuck,
	"Basketball": BallTypeOptionBasketball,
}

func (v BallTypeOption) String() string {
	if s, ok := EnumNamesBallTypeOption[v]; ok {
		return s
	}
	return "BallTypeOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
