// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BoostStrengthOption byte

const (
	BoostStrengthOptionOne         BoostStrengthOption = 0
	BoostStrengthOptionOneAndAHalf BoostStrengthOption = 1
	BoostStrengthOptionTwo         BoostStrengthOption = 2
	BoostStrengthOptionTen         BoostStrengthOption = 3
)

var EnumNamesBoostStrengthOption = map[BoostStrengthOption]string{
	BoostStrengthOptionOne:         "One",
	BoostStrengthOptionOneAndAHalf: "OneAndAHalf",
	BoostStrengthOptionTwo:         "Two",
	BoostStrengthOptionTen:         "Ten",
}

var EnumValuesBoostStrengthOption = map[string]BoostStrengthOption{
	"One":         BoostStrengthOptionOne,
	"OneAndAHalf": BoostStrengthOptionOneAndAHalf,
	"Two":         BoostStrengthOptionTwo,
	"Ten":         BoostStrengthOptionTen,
}

func (v BoostStrengthOption) String() string {
	if s, ok := EnumNamesBoostStrengthOption[v]; ok {
		return s
	}
	return "BoostStrengthOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
