// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type DemolishOption byte

const (
	DemolishOptionDefault       DemolishOption = 0
	DemolishOptionDisabled      DemolishOption = 1
	DemolishOptionFriendly_Fire DemolishOption = 2
	DemolishOptionOn_Contact    DemolishOption = 3
	DemolishOptionOn_Contact_FF DemolishOption = 4
)

var EnumNamesDemolishOption = map[DemolishOption]string{
	DemolishOptionDefault:       "Default",
	DemolishOptionDisabled:      "Disabled",
	DemolishOptionFriendly_Fire: "Friendly_Fire",
	DemolishOptionOn_Contact:    "On_Contact",
	DemolishOptionOn_Contact_FF: "On_Contact_FF",
}

var EnumValuesDemolishOption = map[string]DemolishOption{
	"Default":       DemolishOptionDefault,
	"Disabled":      DemolishOptionDisabled,
	"Friendly_Fire": DemolishOptionFriendly_Fire,
	"On_Contact":    DemolishOptionOn_Contact,
	"On_Contact_FF": DemolishOptionOn_Contact_FF,
}

func (v DemolishOption) String() string {
	if s, ok := EnumNamesDemolishOption[v]; ok {
		return s
	}
	return "DemolishOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
