// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type ExistingMatchBehavior byte

const (
	/// Restart the match if any match settings differ. This is the default because old RLBot always worked this way.
	ExistingMatchBehaviorRestart_If_Different ExistingMatchBehavior = 0
	/// Always restart the match, even if config is identical
	ExistingMatchBehaviorRestart              ExistingMatchBehavior = 1
	/// Never restart an existing match, just try to remove or spawn cars to match the configuration.
	/// If we are not in the middle of a match, a match will be started. Handy for LAN matches.
	ExistingMatchBehaviorContinue_And_Spawn   ExistingMatchBehavior = 2
)

var EnumNamesExistingMatchBehavior = map[ExistingMatchBehavior]string{
	ExistingMatchBehaviorRestart_If_Different: "Restart_If_Different",
	ExistingMatchBehaviorRestart:              "Restart",
	ExistingMatchBehaviorContinue_And_Spawn:   "Continue_And_Spawn",
}

var EnumValuesExistingMatchBehavior = map[string]ExistingMatchBehavior{
	"Restart_If_Different": ExistingMatchBehaviorRestart_If_Different,
	"Restart":              ExistingMatchBehaviorRestart,
	"Continue_And_Spawn":   ExistingMatchBehaviorContinue_And_Spawn,
}

func (v ExistingMatchBehavior) String() string {
	if s, ok := EnumNamesExistingMatchBehavior[v]; ok {
		return s
	}
	return "ExistingMatchBehavior(" + strconv.FormatInt(int64(v), 10) + ")"
}
