// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type GameMode byte

const (
	GameModeSoccer     GameMode = 0
	GameModeHoops      GameMode = 1
	GameModeDropshot   GameMode = 2
	GameModeHockey     GameMode = 3
	GameModeRumble     GameMode = 4
	GameModeHeatseeker GameMode = 5
	GameModeGridiron   GameMode = 6
)

var EnumNamesGameMode = map[GameMode]string{
	GameModeSoccer:     "Soccer",
	GameModeHoops:      "Hoops",
	GameModeDropshot:   "Dropshot",
	GameModeHockey:     "Hockey",
	GameModeRumble:     "Rumble",
	GameModeHeatseeker: "Heatseeker",
	GameModeGridiron:   "Gridiron",
}

var EnumValuesGameMode = map[string]GameMode{
	"Soccer":     GameModeSoccer,
	"Hoops":      GameModeHoops,
	"Dropshot":   GameModeDropshot,
	"Hockey":     GameModeHockey,
	"Rumble":     GameModeRumble,
	"Heatseeker": GameModeHeatseeker,
	"Gridiron":   GameModeGridiron,
}

func (v GameMode) String() string {
	if s, ok := EnumNamesGameMode[v]; ok {
		return s
	}
	return "GameMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
