// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type GameStateType byte

const (
	/// Game has not been created yet
	GameStateTypeInactive   GameStateType = 0
	/// 3-2-1 countdown
	GameStateTypeCountdown  GameStateType = 1
	/// After countdown, but before ball has been hit
	GameStateTypeKickoff    GameStateType = 2
	/// Ball has been hit
	GameStateTypeActive     GameStateType = 3
	/// A goal was scored. Waiting for replay.
	GameStateTypeGoalScored GameStateType = 4
	/// Watching replay
	GameStateTypeReplay     GameStateType = 5
	/// Game paused
	GameStateTypePaused     GameStateType = 6
	/// Match has ended
	GameStateTypeEnded      GameStateType = 7
)

var EnumNamesGameStateType = map[GameStateType]string{
	GameStateTypeInactive:   "Inactive",
	GameStateTypeCountdown:  "Countdown",
	GameStateTypeKickoff:    "Kickoff",
	GameStateTypeActive:     "Active",
	GameStateTypeGoalScored: "GoalScored",
	GameStateTypeReplay:     "Replay",
	GameStateTypePaused:     "Paused",
	GameStateTypeEnded:      "Ended",
}

var EnumValuesGameStateType = map[string]GameStateType{
	"Inactive":   GameStateTypeInactive,
	"Countdown":  GameStateTypeCountdown,
	"Kickoff":    GameStateTypeKickoff,
	"Active":     GameStateTypeActive,
	"GoalScored": GameStateTypeGoalScored,
	"Replay":     GameStateTypeReplay,
	"Paused":     GameStateTypePaused,
	"Ended":      GameStateTypeEnded,
}

func (v GameStateType) String() string {
	if s, ok := EnumNamesGameStateType[v]; ok {
		return s
	}
	return "GameStateType(" + strconv.FormatInt(int64(v), 10) + ")"
}
