// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type StaleBallMutator byte

const (
	StaleBallMutatorUnlimited     StaleBallMutator = 0
	StaleBallMutatorThirtySeconds StaleBallMutator = 1
)

var EnumNamesStaleBallMutator = map[StaleBallMutator]string{
	StaleBallMutatorUnlimited:     "Unlimited",
	StaleBallMutatorThirtySeconds: "ThirtySeconds",
}

var EnumValuesStaleBallMutator = map[string]StaleBallMutator{
	"Unlimited":     StaleBallMutatorUnlimited,
	"ThirtySeconds": StaleBallMutatorThirtySeconds,
}

func (v StaleBallMutator) String() string {
	if s, ok := EnumNamesStaleBallMutator[v]; ok {
		return s
	}
	return "StaleBallMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
