// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type AudioOption byte

const (
	AudioOptionDefault AudioOption = 0
	AudioOptionHaunted AudioOption = 1
)

var EnumNamesAudioOption = map[AudioOption]string{
	AudioOptionDefault: "Default",
	AudioOptionHaunted: "Haunted",
}

var EnumValuesAudioOption = map[string]AudioOption{
	"Default": AudioOptionDefault,
	"Haunted": AudioOptionHaunted,
}

func (v AudioOption) String() string {
	if s, ok := EnumNamesAudioOption[v]; ok {
		return s
	}
	return "AudioOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
