// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Ball weight mutator options.
type BallWeightMutator byte

const (
	BallWeightMutatorDefault        BallWeightMutator = 0
	BallWeightMutatorLight          BallWeightMutator = 1
	BallWeightMutatorHeavy          BallWeightMutator = 2
	BallWeightMutatorSuperLight     BallWeightMutator = 3
	BallWeightMutatorCurveBall      BallWeightMutator = 4
	BallWeightMutatorBeachBallCurve BallWeightMutator = 5
	BallWeightMutatorMagnusFutBall  BallWeightMutator = 6
)

var EnumNamesBallWeightMutator = map[BallWeightMutator]string{
	BallWeightMutatorDefault:        "Default",
	BallWeightMutatorLight:          "Light",
	BallWeightMutatorHeavy:          "Heavy",
	BallWeightMutatorSuperLight:     "SuperLight",
	BallWeightMutatorCurveBall:      "CurveBall",
	BallWeightMutatorBeachBallCurve: "BeachBallCurve",
	BallWeightMutatorMagnusFutBall:  "MagnusFutBall",
}

var EnumValuesBallWeightMutator = map[string]BallWeightMutator{
	"Default":        BallWeightMutatorDefault,
	"Light":          BallWeightMutatorLight,
	"Heavy":          BallWeightMutatorHeavy,
	"SuperLight":     BallWeightMutatorSuperLight,
	"CurveBall":      BallWeightMutatorCurveBall,
	"BeachBallCurve": BallWeightMutatorBeachBallCurve,
	"MagnusFutBall":  BallWeightMutatorMagnusFutBall,
}

func (v BallWeightMutator) String() string {
	if s, ok := EnumNamesBallWeightMutator[v]; ok {
		return s
	}
	return "BallWeightMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
