// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Overtime mutator options.
type OvertimeMutator byte

const (
	OvertimeMutatorUnlimited         OvertimeMutator = 0
	OvertimeMutatorFiveMaxFirstScore OvertimeMutator = 1
	OvertimeMutatorFiveMaxRandomTeam OvertimeMutator = 2
)

var EnumNamesOvertimeMutator = map[OvertimeMutator]string{
	OvertimeMutatorUnlimited:         "Unlimited",
	OvertimeMutatorFiveMaxFirstScore: "FiveMaxFirstScore",
	OvertimeMutatorFiveMaxRandomTeam: "FiveMaxRandomTeam",
}

var EnumValuesOvertimeMutator = map[string]OvertimeMutator{
	"Unlimited":         OvertimeMutatorUnlimited,
	"FiveMaxFirstScore": OvertimeMutatorFiveMaxFirstScore,
	"FiveMaxRandomTeam": OvertimeMutatorFiveMaxRandomTeam,
}

func (v OvertimeMutator) String() string {
	if s, ok := EnumNamesOvertimeMutator[v]; ok {
		return s
	}
	return "OvertimeMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
