// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type Launcher byte

const (
	LauncherSteam  Launcher = 0
	LauncherEpic   Launcher = 1
	LauncherCustom Launcher = 2
)

var EnumNamesLauncher = map[Launcher]string{
	LauncherSteam:  "Steam",
	LauncherEpic:   "Epic",
	LauncherCustom: "Custom",
}

var EnumValuesLauncher = map[string]Launcher{
	"Steam":  LauncherSteam,
	"Epic":   LauncherEpic,
	"Custom": LauncherCustom,
}

func (v Launcher) String() string {
	if s, ok := EnumNamesLauncher[v]; ok {
		return s
	}
	return "Launcher(" + strconv.FormatInt(int64(v), 10) + ")"
}
