// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type DemolishScoreMutator byte

const (
	DemolishScoreMutatorZero  DemolishScoreMutator = 0
	DemolishScoreMutatorOne   DemolishScoreMutator = 1
	DemolishScoreMutatorTwo   DemolishScoreMutator = 2
	DemolishScoreMutatorThree DemolishScoreMutator = 3
)

var EnumNamesDemolishScoreMutator = map[DemolishScoreMutator]string{
	DemolishScoreMutatorZero:  "Zero",
	DemolishScoreMutatorOne:   "One",
	DemolishScoreMutatorTwo:   "Two",
	DemolishScoreMutatorThree: "Three",
}

var EnumValuesDemolishScoreMutator = map[string]DemolishScoreMutator{
	"Zero":  DemolishScoreMutatorZero,
	"One":   DemolishScoreMutatorOne,
	"Two":   DemolishScoreMutatorTwo,
	"Three": DemolishScoreMutatorThree,
}

func (v DemolishScoreMutator) String() string {
	if s, ok := EnumNamesDemolishScoreMutator[v]; ok {
		return s
	}
	return "DemolishScoreMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
