// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type JumpMutator byte

const (
	JumpMutatorDefault   JumpMutator = 0
	JumpMutatorGrounded  JumpMutator = 1
	JumpMutatorTwo       JumpMutator = 2
	JumpMutatorThree     JumpMutator = 3
	JumpMutatorFour      JumpMutator = 4
	JumpMutatorUnlimited JumpMutator = 5
	JumpMutatorNoJumps   JumpMutator = 6
)

var EnumNamesJumpMutator = map[JumpMutator]string{
	JumpMutatorDefault:   "Default",
	JumpMutatorGrounded:  "Grounded",
	JumpMutatorTwo:       "Two",
	JumpMutatorThree:     "Three",
	JumpMutatorFour:      "Four",
	JumpMutatorUnlimited: "Unlimited",
	JumpMutatorNoJumps:   "NoJumps",
}

var EnumValuesJumpMutator = map[string]JumpMutator{
	"Default":   JumpMutatorDefault,
	"Grounded":  JumpMutatorGrounded,
	"Two":       JumpMutatorTwo,
	"Three":     JumpMutatorThree,
	"Four":      JumpMutatorFour,
	"Unlimited": JumpMutatorUnlimited,
	"NoJumps":   JumpMutatorNoJumps,
}

func (v JumpMutator) String() string {
	if s, ok := EnumNamesJumpMutator[v]; ok {
		return s
	}
	return "JumpMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
