// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A client message request removal of a RenderGroup.
/// A client can only clear its own RenderGroups.
type RemoveRenderGroupT struct {
	Id int32 `json:"id"`
}

func (t *RemoveRenderGroupT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	RemoveRenderGroupStart(builder)
	RemoveRenderGroupAddId(builder, t.Id)
	return RemoveRenderGroupEnd(builder)
}

func (rcv *RemoveRenderGroup) UnPackTo(t *RemoveRenderGroupT) {
	t.Id = rcv.Id()
}

func (rcv *RemoveRenderGroup) UnPack() *RemoveRenderGroupT {
	if rcv == nil {
		return nil
	}
	t := &RemoveRenderGroupT{}
	rcv.UnPackTo(t)
	return t
}

type RemoveRenderGroup struct {
	_tab flatbuffers.Table
}

func GetRootAsRemoveRenderGroup(buf []byte, offset flatbuffers.UOffsetT) *RemoveRenderGroup {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RemoveRenderGroup{}
	x.Init(buf, n+offset)
	return x
}

func FinishRemoveRenderGroupBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRemoveRenderGroup(buf []byte, offset flatbuffers.UOffsetT) *RemoveRenderGroup {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RemoveRenderGroup{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRemoveRenderGroupBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RemoveRenderGroup) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RemoveRenderGroup) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RemoveRenderGroup) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RemoveRenderGroup) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func RemoveRenderGroupStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RemoveRenderGroupAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func RemoveRenderGroupEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
