// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A vector with an x and y component.
type Vector2T struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

func (t *Vector2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateVector2(builder, t.X, t.Y)
}
func (rcv *Vector2) UnPackTo(t *Vector2T) {
	t.X = rcv.X()
	t.Y = rcv.Y()
}

func (rcv *Vector2) UnPack() *Vector2T {
	if rcv == nil {
		return nil
	}
	t := &Vector2T{}
	rcv.UnPackTo(t)
	return t
}

type Vector2 struct {
	_tab flatbuffers.Struct
}

func (rcv *Vector2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector2) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Vector2) X() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vector2) MutateX(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vector2) Y() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Vector2) MutateY(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateVector2(builder *flatbuffers.Builder, x float32, y float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(y)
	builder.PrependFloat32(x)
	return builder.Offset()
}
