// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Boost amount mutator options.
type BoostAmountMutator byte

const (
	BoostAmountMutatorNormalBoost    BoostAmountMutator = 0
	BoostAmountMutatorUnlimitedBoost BoostAmountMutator = 1
	BoostAmountMutatorSlowRecharge   BoostAmountMutator = 2
	BoostAmountMutatorRapidRecharge  BoostAmountMutator = 3
	BoostAmountMutatorNoBoost        BoostAmountMutator = 4
)

var EnumNamesBoostAmountMutator = map[BoostAmountMutator]string{
	BoostAmountMutatorNormalBoost:    "NormalBoost",
	BoostAmountMutatorUnlimitedBoost: "UnlimitedBoost",
	BoostAmountMutatorSlowRecharge:   "SlowRecharge",
	BoostAmountMutatorRapidRecharge:  "RapidRecharge",
	BoostAmountMutatorNoBoost:        "NoBoost",
}

var EnumValuesBoostAmountMutator = map[string]BoostAmountMutator{
	"NormalBoost":    BoostAmountMutatorNormalBoost,
	"UnlimitedBoost": BoostAmountMutatorUnlimitedBoost,
	"SlowRecharge":   BoostAmountMutatorSlowRecharge,
	"RapidRecharge":  BoostAmountMutatorRapidRecharge,
	"NoBoost":        BoostAmountMutatorNoBoost,
}

func (v BoostAmountMutator) String() string {
	if s, ok := EnumNamesBoostAmountMutator[v]; ok {
		return s
	}
	return "BoostAmountMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
