// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type DodgeTimerMutator byte

const (
	DodgeTimerMutatorOnePointTwentyFiveSeconds DodgeTimerMutator = 0
	DodgeTimerMutatorTwoSeconds                DodgeTimerMutator = 1
	DodgeTimerMutatorThreeSeconds              DodgeTimerMutator = 2
	DodgeTimerMutatorUnlimited                 DodgeTimerMutator = 3
)

var EnumNamesDodgeTimerMutator = map[DodgeTimerMutator]string{
	DodgeTimerMutatorOnePointTwentyFiveSeconds: "OnePointTwentyFiveSeconds",
	DodgeTimerMutatorTwoSeconds:                "TwoSeconds",
	DodgeTimerMutatorThreeSeconds:              "ThreeSeconds",
	DodgeTimerMutatorUnlimited:                 "Unlimited",
}

var EnumValuesDodgeTimerMutator = map[string]DodgeTimerMutator{
	"OnePointTwentyFiveSeconds": DodgeTimerMutatorOnePointTwentyFiveSeconds,
	"TwoSeconds":                DodgeTimerMutatorTwoSeconds,
	"ThreeSeconds":              DodgeTimerMutatorThreeSeconds,
	"Unlimited":                 DodgeTimerMutatorUnlimited,
}

func (v DodgeTimerMutator) String() string {
	if s, ok := EnumNamesDodgeTimerMutator[v]; ok {
		return s
	}
	return "DodgeTimerMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
