// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type InputRestrictionMutator byte

const (
	InputRestrictionMutatorDefault   InputRestrictionMutator = 0
	InputRestrictionMutatorBackwards InputRestrictionMutator = 1
)

var EnumNamesInputRestrictionMutator = map[InputRestrictionMutator]string{
	InputRestrictionMutatorDefault:   "Default",
	InputRestrictionMutatorBackwards: "Backwards",
}

var EnumValuesInputRestrictionMutator = map[string]InputRestrictionMutator{
	"Default":   InputRestrictionMutatorDefault,
	"Backwards": InputRestrictionMutatorBackwards,
}

func (v InputRestrictionMutator) String() string {
	if s, ok := EnumNamesInputRestrictionMutator[v]; ok {
		return s
	}
	return "InputRestrictionMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
