// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type NormalGoalScoreMutator byte

const (
	NormalGoalScoreMutatorDefault NormalGoalScoreMutator = 0
	NormalGoalScoreMutatorZero    NormalGoalScoreMutator = 1
	NormalGoalScoreMutatorTwo     NormalGoalScoreMutator = 2
	NormalGoalScoreMutatorThree   NormalGoalScoreMutator = 3
	NormalGoalScoreMutatorFive    NormalGoalScoreMutator = 4
	NormalGoalScoreMutatorTen     NormalGoalScoreMutator = 5
)

var EnumNamesNormalGoalScoreMutator = map[NormalGoalScoreMutator]string{
	NormalGoalScoreMutatorDefault: "Default",
	NormalGoalScoreMutatorZero:    "Zero",
	NormalGoalScoreMutatorTwo:     "Two",
	NormalGoalScoreMutatorThree:   "Three",
	NormalGoalScoreMutatorFive:    "Five",
	NormalGoalScoreMutatorTen:     "Ten",
}

var EnumValuesNormalGoalScoreMutator = map[string]NormalGoalScoreMutator{
	"Default": NormalGoalScoreMutatorDefault,
	"Zero":    NormalGoalScoreMutatorZero,
	"Two":     NormalGoalScoreMutatorTwo,
	"Three":   NormalGoalScoreMutatorThree,
	"Five":    NormalGoalScoreMutatorFive,
	"Ten":     NormalGoalScoreMutatorTen,
}

func (v NormalGoalScoreMutator) String() string {
	if s, ok := EnumNamesNormalGoalScoreMutator[v]; ok {
		return s
	}
	return "NormalGoalScoreMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
