// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Series length mutator options.
type SeriesLengthMutator byte

const (
	SeriesLengthMutatorUnlimited  SeriesLengthMutator = 0
	SeriesLengthMutatorThreeGames SeriesLengthMutator = 1
	SeriesLengthMutatorFiveGames  SeriesLengthMutator = 2
	SeriesLengthMutatorSevenGames SeriesLengthMutator = 3
)

var EnumNamesSeriesLengthMutator = map[SeriesLengthMutator]string{
	SeriesLengthMutatorUnlimited:  "Unlimited",
	SeriesLengthMutatorThreeGames: "ThreeGames",
	SeriesLengthMutatorFiveGames:  "FiveGames",
	SeriesLengthMutatorSevenGames: "SevenGames",
}

var EnumValuesSeriesLengthMutator = map[string]SeriesLengthMutator{
	"Unlimited":  SeriesLengthMutatorUnlimited,
	"ThreeGames": SeriesLengthMutatorThreeGames,
	"FiveGames":  SeriesLengthMutatorFiveGames,
	"SevenGames": SeriesLengthMutatorSevenGames,
}

func (v SeriesLengthMutator) String() string {
	if s, ok := EnumNamesSeriesLengthMutator[v]; ok {
		return s
	}
	return "SeriesLengthMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
