// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BoostOption byte

const (
	BoostOptionNormal_Boost    BoostOption = 0
	BoostOptionUnlimited_Boost BoostOption = 1
	BoostOptionSlow_Recharge   BoostOption = 2
	BoostOptionRapid_Recharge  BoostOption = 3
	BoostOptionNo_Boost        BoostOption = 4
)

var EnumNamesBoostOption = map[BoostOption]string{
	BoostOptionNormal_Boost:    "Normal_Boost",
	BoostOptionUnlimited_Boost: "Unlimited_Boost",
	BoostOptionSlow_Recharge:   "Slow_Recharge",
	BoostOptionRapid_Recharge:  "Rapid_Recharge",
	BoostOptionNo_Boost:        "No_Boost",
}

var EnumValuesBoostOption = map[string]BoostOption{
	"Normal_Boost":    BoostOptionNormal_Boost,
	"Unlimited_Boost": BoostOptionUnlimited_Boost,
	"Slow_Recharge":   BoostOptionSlow_Recharge,
	"Rapid_Recharge":  BoostOptionRapid_Recharge,
	"No_Boost":        BoostOptionNo_Boost,
}

func (v BoostOption) String() string {
	if s, ok := EnumNamesBoostOption[v]; ok {
		return s
	}
	return "BoostOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
