// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type PossessionScoreMutator byte

const (
	PossessionScoreMutatorDefault      PossessionScoreMutator = 0
	PossessionScoreMutatorOneSecond    PossessionScoreMutator = 1
	PossessionScoreMutatorTwoSeconds   PossessionScoreMutator = 2
	PossessionScoreMutatorThreeSeconds PossessionScoreMutator = 3
)

var EnumNamesPossessionScoreMutator = map[PossessionScoreMutator]string{
	PossessionScoreMutatorDefault:      "Default",
	PossessionScoreMutatorOneSecond:    "OneSecond",
	PossessionScoreMutatorTwoSeconds:   "TwoSeconds",
	PossessionScoreMutatorThreeSeconds: "ThreeSeconds",
}

var EnumValuesPossessionScoreMutator = map[string]PossessionScoreMutator{
	"Default":      PossessionScoreMutatorDefault,
	"OneSecond":    PossessionScoreMutatorOneSecond,
	"TwoSeconds":   PossessionScoreMutatorTwoSeconds,
	"ThreeSeconds": PossessionScoreMutatorThreeSeconds,
}

func (v PossessionScoreMutator) String() string {
	if s, ok := EnumNamesPossessionScoreMutator[v]; ok {
		return s
	}
	return "PossessionScoreMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
