// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type TerritoryMutator byte

const (
	TerritoryMutatorDefault   TerritoryMutator = 0
	TerritoryMutatorTerritory TerritoryMutator = 1
)

var EnumNamesTerritoryMutator = map[TerritoryMutator]string{
	TerritoryMutatorDefault:   "Default",
	TerritoryMutatorTerritory: "Territory",
}

var EnumValuesTerritoryMutator = map[string]TerritoryMutator{
	"Default":   TerritoryMutatorDefault,
	"Territory": TerritoryMutatorTerritory,
}

func (v TerritoryMutator) String() string {
	if s, ok := EnumNamesTerritoryMutator[v]; ok {
		return s
	}
	return "TerritoryMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
