// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type BallBouncinessOption byte

const (
	BallBouncinessOptionDefault          BallBouncinessOption = 0
	BallBouncinessOptionLow              BallBouncinessOption = 1
	BallBouncinessOptionHigh             BallBouncinessOption = 2
	BallBouncinessOptionSuper_High       BallBouncinessOption = 3
	BallBouncinessOptionLowishBounciness BallBouncinessOption = 4
)

var EnumNamesBallBouncinessOption = map[BallBouncinessOption]string{
	BallBouncinessOptionDefault:          "Default",
	BallBouncinessOptionLow:              "Low",
	BallBouncinessOptionHigh:             "High",
	BallBouncinessOptionSuper_High:       "Super_High",
	BallBouncinessOptionLowishBounciness: "LowishBounciness",
}

var EnumValuesBallBouncinessOption = map[string]BallBouncinessOption{
	"Default":          BallBouncinessOptionDefault,
	"Low":              BallBouncinessOptionLow,
	"High":             BallBouncinessOptionHigh,
	"Super_High":       BallBouncinessOptionSuper_High,
	"LowishBounciness": BallBouncinessOptionLowishBounciness,
}

func (v BallBouncinessOption) String() string {
	if s, ok := EnumNamesBallBouncinessOption[v]; ok {
		return s
	}
	return "BallBouncinessOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
