// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BallAnchorT struct {
	Index uint32 `json:"index"`
	Local *Vector3T `json:"local"`
}

func (t *BallAnchorT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	BallAnchorStart(builder)
	BallAnchorAddIndex(builder, t.Index)
	localOffset := t.Local.Pack(builder)
	BallAnchorAddLocal(builder, localOffset)
	return BallAnchorEnd(builder)
}

func (rcv *BallAnchor) UnPackTo(t *BallAnchorT) {
	t.Index = rcv.Index()
	t.Local = rcv.Local(nil).UnPack()
}

func (rcv *BallAnchor) UnPack() *BallAnchorT {
	if rcv == nil {
		return nil
	}
	t := &BallAnchorT{}
	rcv.UnPackTo(t)
	return t
}

type BallAnchor struct {
	_tab flatbuffers.Table
}

func GetRootAsBallAnchor(buf []byte, offset flatbuffers.UOffsetT) *BallAnchor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BallAnchor{}
	x.Init(buf, n+offset)
	return x
}

func FinishBallAnchorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBallAnchor(buf []byte, offset flatbuffers.UOffsetT) *BallAnchor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BallAnchor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBallAnchorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BallAnchor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BallAnchor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BallAnchor) Index() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BallAnchor) MutateIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *BallAnchor) Local(obj *Vector3) *Vector3 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector3)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BallAnchorStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BallAnchorAddIndex(builder *flatbuffers.Builder, index uint32) {
	builder.PrependUint32Slot(0, index, 0)
}
func BallAnchorAddLocal(builder *flatbuffers.Builder, local flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(local), 0)
}
func BallAnchorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
