// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A game state with nullable subcomponents.
/// Used for game state setting to define which part of the game should change.
/// Values not set will not be updated.
type DesiredGameStateT struct {
	BallStates []*DesiredBallStateT `json:"ball_states"`
	CarStates []*DesiredCarStateT `json:"car_states"`
	MatchInfo *DesiredMatchInfoT `json:"match_info"`
	ConsoleCommands []*ConsoleCommandT `json:"console_commands"`
}

func (t *DesiredGameStateT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	ballStatesOffset := flatbuffers.UOffsetT(0)
	if t.BallStates != nil {
		ballStatesLength := len(t.BallStates)
		ballStatesOffsets := make([]flatbuffers.UOffsetT, ballStatesLength)
		for j := 0; j < ballStatesLength; j++ {
			ballStatesOffsets[j] = t.BallStates[j].Pack(builder)
		}
		DesiredGameStateStartBallStatesVector(builder, ballStatesLength)
		for j := ballStatesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(ballStatesOffsets[j])
		}
		ballStatesOffset = builder.EndVector(ballStatesLength)
	}
	carStatesOffset := flatbuffers.UOffsetT(0)
	if t.CarStates != nil {
		carStatesLength := len(t.CarStates)
		carStatesOffsets := make([]flatbuffers.UOffsetT, carStatesLength)
		for j := 0; j < carStatesLength; j++ {
			carStatesOffsets[j] = t.CarStates[j].Pack(builder)
		}
		DesiredGameStateStartCarStatesVector(builder, carStatesLength)
		for j := carStatesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(carStatesOffsets[j])
		}
		carStatesOffset = builder.EndVector(carStatesLength)
	}
	matchInfoOffset := t.MatchInfo.Pack(builder)
	consoleCommandsOffset := flatbuffers.UOffsetT(0)
	if t.ConsoleCommands != nil {
		consoleCommandsLength := len(t.ConsoleCommands)
		consoleCommandsOffsets := make([]flatbuffers.UOffsetT, consoleCommandsLength)
		for j := 0; j < consoleCommandsLength; j++ {
			consoleCommandsOffsets[j] = t.ConsoleCommands[j].Pack(builder)
		}
		DesiredGameStateStartConsoleCommandsVector(builder, consoleCommandsLength)
		for j := consoleCommandsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(consoleCommandsOffsets[j])
		}
		consoleCommandsOffset = builder.EndVector(consoleCommandsLength)
	}
	DesiredGameStateStart(builder)
	DesiredGameStateAddBallStates(builder, ballStatesOffset)
	DesiredGameStateAddCarStates(builder, carStatesOffset)
	DesiredGameStateAddMatchInfo(builder, matchInfoOffset)
	DesiredGameStateAddConsoleCommands(builder, consoleCommandsOffset)
	return DesiredGameStateEnd(builder)
}

func (rcv *DesiredGameState) UnPackTo(t *DesiredGameStateT) {
	ballStatesLength := rcv.BallStatesLength()
	t.BallStates = make([]*DesiredBallStateT, ballStatesLength)
	for j := 0; j < ballStatesLength; j++ {
		x := DesiredBallState{}
		rcv.BallStates(&x, j)
		t.BallStates[j] = x.UnPack()
	}
	carStatesLength := rcv.CarStatesLength()
	t.CarStates = make([]*DesiredCarStateT, carStatesLength)
	for j := 0; j < carStatesLength; j++ {
		x := DesiredCarState{}
		rcv.CarStates(&x, j)
		t.CarStates[j] = x.UnPack()
	}
	t.MatchInfo = rcv.MatchInfo(nil).UnPack()
	consoleCommandsLength := rcv.ConsoleCommandsLength()
	t.ConsoleCommands = make([]*ConsoleCommandT, consoleCommandsLength)
	for j := 0; j < consoleCommandsLength; j++ {
		x := ConsoleCommand{}
		rcv.ConsoleCommands(&x, j)
		t.ConsoleCommands[j] = x.UnPack()
	}
}

func (rcv *DesiredGameState) UnPack() *DesiredGameStateT {
	if rcv == nil {
		return nil
	}
	t := &DesiredGameStateT{}
	rcv.UnPackTo(t)
	return t
}

type DesiredGameState struct {
	_tab flatbuffers.Table
}

func GetRootAsDesiredGameState(buf []byte, offset flatbuffers.UOffsetT) *DesiredGameState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DesiredGameState{}
	x.Init(buf, n+offset)
	return x
}

func FinishDesiredGameStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDesiredGameState(buf []byte, offset flatbuffers.UOffsetT) *DesiredGameState {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DesiredGameState{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDesiredGameStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DesiredGameState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DesiredGameState) Table() flatbuffers.Table {
	return rcv._tab
}

/// A list of desired ball states.
func (rcv *DesiredGameState) BallStates(obj *DesiredBallState, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DesiredGameState) BallStatesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// A list of desired ball states.
/// A list of desired car states.
func (rcv *DesiredGameState) CarStates(obj *DesiredCarState, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DesiredGameState) CarStatesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// A list of desired car states.
/// The desired game info.
func (rcv *DesiredGameState) MatchInfo(obj *DesiredMatchInfo) *DesiredMatchInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DesiredMatchInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// The desired game info.
/// A list of console commands to execute.
/// See https://wiki.rlbot.org/framework/console-commands/ for a list of known commands.
func (rcv *DesiredGameState) ConsoleCommands(obj *ConsoleCommand, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DesiredGameState) ConsoleCommandsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// A list of console commands to execute.
/// See https://wiki.rlbot.org/framework/console-commands/ for a list of known commands.
func DesiredGameStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DesiredGameStateAddBallStates(builder *flatbuffers.Builder, ballStates flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ballStates), 0)
}
func DesiredGameStateStartBallStatesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DesiredGameStateAddCarStates(builder *flatbuffers.Builder, carStates flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(carStates), 0)
}
func DesiredGameStateStartCarStatesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DesiredGameStateAddMatchInfo(builder *flatbuffers.Builder, matchInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(matchInfo), 0)
}
func DesiredGameStateAddConsoleCommands(builder *flatbuffers.Builder, consoleCommands flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(consoleCommands), 0)
}
func DesiredGameStateStartConsoleCommandsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DesiredGameStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
