// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Ball size mutator options.
type BallSizeMutator byte

const (
	BallSizeMutatorDefault  BallSizeMutator = 0
	BallSizeMutatorSmall    BallSizeMutator = 1
	BallSizeMutatorMedium   BallSizeMutator = 2
	BallSizeMutatorLarge    BallSizeMutator = 3
	BallSizeMutatorGigantic BallSizeMutator = 4
)

var EnumNamesBallSizeMutator = map[BallSizeMutator]string{
	BallSizeMutatorDefault:  "Default",
	BallSizeMutatorSmall:    "Small",
	BallSizeMutatorMedium:   "Medium",
	BallSizeMutatorLarge:    "Large",
	BallSizeMutatorGigantic: "Gigantic",
}

var EnumValuesBallSizeMutator = map[string]BallSizeMutator{
	"Default":  BallSizeMutatorDefault,
	"Small":    BallSizeMutatorSmall,
	"Medium":   BallSizeMutatorMedium,
	"Large":    BallSizeMutatorLarge,
	"Gigantic": BallSizeMutatorGigantic,
}

func (v BallSizeMutator) String() string {
	if s, ok := EnumNamesBallSizeMutator[v]; ok {
		return s
	}
	return "BallSizeMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
