// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Demolition mutator options.
type DemolishMutator byte

const (
	DemolishMutatorDefault         DemolishMutator = 0
	DemolishMutatorDisabled        DemolishMutator = 1
	DemolishMutatorFriendlyFire    DemolishMutator = 2
	DemolishMutatorOnContact       DemolishMutator = 3
	DemolishMutatorOnContactFF     DemolishMutator = 4
	DemolishMutatorOnBallContact   DemolishMutator = 5
	DemolishMutatorOnBallContactFF DemolishMutator = 6
)

var EnumNamesDemolishMutator = map[DemolishMutator]string{
	DemolishMutatorDefault:         "Default",
	DemolishMutatorDisabled:        "Disabled",
	DemolishMutatorFriendlyFire:    "FriendlyFire",
	DemolishMutatorOnContact:       "OnContact",
	DemolishMutatorOnContactFF:     "OnContactFF",
	DemolishMutatorOnBallContact:   "OnBallContact",
	DemolishMutatorOnBallContactFF: "OnBallContactFF",
}

var EnumValuesDemolishMutator = map[string]DemolishMutator{
	"Default":         DemolishMutatorDefault,
	"Disabled":        DemolishMutatorDisabled,
	"FriendlyFire":    DemolishMutatorFriendlyFire,
	"OnContact":       DemolishMutatorOnContact,
	"OnContactFF":     DemolishMutatorOnContactFF,
	"OnBallContact":   DemolishMutatorOnBallContact,
	"OnBallContactFF": DemolishMutatorOnBallContactFF,
}

func (v DemolishMutator) String() string {
	if s, ok := EnumNamesDemolishMutator[v]; ok {
		return s
	}
	return "DemolishMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
