// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Ball max speed mutator options.
type BallMaxSpeedMutator byte

const (
	BallMaxSpeedMutatorDefault   BallMaxSpeedMutator = 0
	BallMaxSpeedMutatorSlow      BallMaxSpeedMutator = 1
	BallMaxSpeedMutatorFast      BallMaxSpeedMutator = 2
	BallMaxSpeedMutatorSuperFast BallMaxSpeedMutator = 3
)

var EnumNamesBallMaxSpeedMutator = map[BallMaxSpeedMutator]string{
	BallMaxSpeedMutatorDefault:   "Default",
	BallMaxSpeedMutatorSlow:      "Slow",
	BallMaxSpeedMutatorFast:      "Fast",
	BallMaxSpeedMutatorSuperFast: "SuperFast",
}

var EnumValuesBallMaxSpeedMutator = map[string]BallMaxSpeedMutator{
	"Default":   BallMaxSpeedMutatorDefault,
	"Slow":      BallMaxSpeedMutatorSlow,
	"Fast":      BallMaxSpeedMutatorFast,
	"SuperFast": BallMaxSpeedMutatorSuperFast,
}

func (v BallMaxSpeedMutator) String() string {
	if s, ok := EnumNamesBallMaxSpeedMutator[v]; ok {
		return s
	}
	return "BallMaxSpeedMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
