// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Boost strength mutator options.
type BoostStrengthMutator byte

const (
	BoostStrengthMutatorOne         BoostStrengthMutator = 0
	BoostStrengthMutatorOneAndAHalf BoostStrengthMutator = 1
	BoostStrengthMutatorTwo         BoostStrengthMutator = 2
	BoostStrengthMutatorFive        BoostStrengthMutator = 3
	BoostStrengthMutatorTen         BoostStrengthMutator = 4
)

var EnumNamesBoostStrengthMutator = map[BoostStrengthMutator]string{
	BoostStrengthMutatorOne:         "One",
	BoostStrengthMutatorOneAndAHalf: "OneAndAHalf",
	BoostStrengthMutatorTwo:         "Two",
	BoostStrengthMutatorFive:        "Five",
	BoostStrengthMutatorTen:         "Ten",
}

var EnumValuesBoostStrengthMutator = map[string]BoostStrengthMutator{
	"One":         BoostStrengthMutatorOne,
	"OneAndAHalf": BoostStrengthMutatorOneAndAHalf,
	"Two":         BoostStrengthMutatorTwo,
	"Five":        BoostStrengthMutatorFive,
	"Ten":         BoostStrengthMutatorTen,
}

func (v BoostStrengthMutator) String() string {
	if s, ok := EnumNamesBoostStrengthMutator[v]; ok {
		return s
	}
	return "BoostStrengthMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
