// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Multi ball mutator options.
type MultiBallMutator byte

const (
	MultiBallMutatorOne  MultiBallMutator = 0
	MultiBallMutatorTwo  MultiBallMutator = 1
	MultiBallMutatorFour MultiBallMutator = 2
	MultiBallMutatorSix  MultiBallMutator = 3
)

var EnumNamesMultiBallMutator = map[MultiBallMutator]string{
	MultiBallMutatorOne:  "One",
	MultiBallMutatorTwo:  "Two",
	MultiBallMutatorFour: "Four",
	MultiBallMutatorSix:  "Six",
}

var EnumValuesMultiBallMutator = map[string]MultiBallMutator{
	"One":  MultiBallMutatorOne,
	"Two":  MultiBallMutatorTwo,
	"Four": MultiBallMutatorFour,
	"Six":  MultiBallMutatorSix,
}

func (v MultiBallMutator) String() string {
	if s, ok := EnumNamesMultiBallMutator[v]; ok {
		return s
	}
	return "MultiBallMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
