// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

/// Max score mutator options.
type MaxScoreMutator byte

const (
	MaxScoreMutatorUnlimited    MaxScoreMutator = 0
	MaxScoreMutatorOneGoal      MaxScoreMutator = 1
	MaxScoreMutatorThreeGoals   MaxScoreMutator = 2
	MaxScoreMutatorFiveGoals    MaxScoreMutator = 3
	MaxScoreMutatorSevenGoals   MaxScoreMutator = 4
	MaxScoreMutatorTenGoals     MaxScoreMutator = 5
	MaxScoreMutatorTwentyGoals  MaxScoreMutator = 6
	MaxScoreMutatorThirtyGoals  MaxScoreMutator = 7
	MaxScoreMutatorFortyGoals   MaxScoreMutator = 8
	MaxScoreMutatorFiftyGoals   MaxScoreMutator = 9
	MaxScoreMutatorSixtyGoals   MaxScoreMutator = 10
	MaxScoreMutatorSeventyGoals MaxScoreMutator = 11
	MaxScoreMutatorEightyGoals  MaxScoreMutator = 12
	MaxScoreMutatorNinetyGoals  MaxScoreMutator = 13
	MaxScoreMutatorHundredGoals MaxScoreMutator = 14
)

var EnumNamesMaxScoreMutator = map[MaxScoreMutator]string{
	MaxScoreMutatorUnlimited:    "Unlimited",
	MaxScoreMutatorOneGoal:      "OneGoal",
	MaxScoreMutatorThreeGoals:   "ThreeGoals",
	MaxScoreMutatorFiveGoals:    "FiveGoals",
	MaxScoreMutatorSevenGoals:   "SevenGoals",
	MaxScoreMutatorTenGoals:     "TenGoals",
	MaxScoreMutatorTwentyGoals:  "TwentyGoals",
	MaxScoreMutatorThirtyGoals:  "ThirtyGoals",
	MaxScoreMutatorFortyGoals:   "FortyGoals",
	MaxScoreMutatorFiftyGoals:   "FiftyGoals",
	MaxScoreMutatorSixtyGoals:   "SixtyGoals",
	MaxScoreMutatorSeventyGoals: "SeventyGoals",
	MaxScoreMutatorEightyGoals:  "EightyGoals",
	MaxScoreMutatorNinetyGoals:  "NinetyGoals",
	MaxScoreMutatorHundredGoals: "HundredGoals",
}

var EnumValuesMaxScoreMutator = map[string]MaxScoreMutator{
	"Unlimited":    MaxScoreMutatorUnlimited,
	"OneGoal":      MaxScoreMutatorOneGoal,
	"ThreeGoals":   MaxScoreMutatorThreeGoals,
	"FiveGoals":    MaxScoreMutatorFiveGoals,
	"SevenGoals":   MaxScoreMutatorSevenGoals,
	"TenGoals":     MaxScoreMutatorTenGoals,
	"TwentyGoals":  MaxScoreMutatorTwentyGoals,
	"ThirtyGoals":  MaxScoreMutatorThirtyGoals,
	"FortyGoals":   MaxScoreMutatorFortyGoals,
	"FiftyGoals":   MaxScoreMutatorFiftyGoals,
	"SixtyGoals":   MaxScoreMutatorSixtyGoals,
	"SeventyGoals": MaxScoreMutatorSeventyGoals,
	"EightyGoals":  MaxScoreMutatorEightyGoals,
	"NinetyGoals":  MaxScoreMutatorNinetyGoals,
	"HundredGoals": MaxScoreMutatorHundredGoals,
}

func (v MaxScoreMutator) String() string {
	if s, ok := EnumNamesMaxScoreMutator[v]; ok {
		return s
	}
	return "MaxScoreMutator(" + strconv.FormatInt(int64(v), 10) + ")"
}
