// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type GravityOption byte

const (
	GravityOptionDefault    GravityOption = 0
	GravityOptionLow        GravityOption = 1
	GravityOptionHigh       GravityOption = 2
	GravityOptionSuper_High GravityOption = 3
)

var EnumNamesGravityOption = map[GravityOption]string{
	GravityOptionDefault:    "Default",
	GravityOptionLow:        "Low",
	GravityOptionHigh:       "High",
	GravityOptionSuper_High: "Super_High",
}

var EnumValuesGravityOption = map[string]GravityOption{
	"Default":    GravityOptionDefault,
	"Low":        GravityOptionLow,
	"High":       GravityOptionHigh,
	"Super_High": GravityOptionSuper_High,
}

func (v GravityOption) String() string {
	if s, ok := EnumNamesGravityOption[v]; ok {
		return s
	}
	return "GravityOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
