// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type MaxScore byte

const (
	MaxScoreUnlimited   MaxScore = 0
	MaxScoreOne_Goal    MaxScore = 1
	MaxScoreThree_Goals MaxScore = 2
	MaxScoreFive_Goals  MaxScore = 3
)

var EnumNamesMaxScore = map[MaxScore]string{
	MaxScoreUnlimited:   "Unlimited",
	MaxScoreOne_Goal:    "One_Goal",
	MaxScoreThree_Goals: "Three_Goals",
	MaxScoreFive_Goals:  "Five_Goals",
}

var EnumValuesMaxScore = map[string]MaxScore{
	"Unlimited":   MaxScoreUnlimited,
	"One_Goal":    MaxScoreOne_Goal,
	"Three_Goals": MaxScoreThree_Goals,
	"Five_Goals":  MaxScoreFive_Goals,
}

func (v MaxScore) String() string {
	if s, ok := EnumNamesMaxScore[v]; ok {
		return s
	}
	return "MaxScore(" + strconv.FormatInt(int64(v), 10) + ")"
}
