// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type MultiBall byte

const (
	MultiBallOne  MultiBall = 0
	MultiBallTwo  MultiBall = 1
	MultiBallFour MultiBall = 2
	MultiBallSix  MultiBall = 3
)

var EnumNamesMultiBall = map[MultiBall]string{
	MultiBallOne:  "One",
	MultiBallTwo:  "Two",
	MultiBallFour: "Four",
	MultiBallSix:  "Six",
}

var EnumValuesMultiBall = map[string]MultiBall{
	"One":  MultiBallOne,
	"Two":  MultiBallTwo,
	"Four": MultiBallFour,
	"Six":  MultiBallSix,
}

func (v MultiBall) String() string {
	if s, ok := EnumNamesMultiBall[v]; ok {
		return s
	}
	return "MultiBall(" + strconv.FormatInt(int64(v), 10) + ")"
}
