// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type OvertimeOption byte

const (
	OvertimeOptionUnlimited            OvertimeOption = 0
	OvertimeOptionFive_Max_First_Score OvertimeOption = 1
	OvertimeOptionFive_Max_Random_Team OvertimeOption = 2
)

var EnumNamesOvertimeOption = map[OvertimeOption]string{
	OvertimeOptionUnlimited:            "Unlimited",
	OvertimeOptionFive_Max_First_Score: "Five_Max_First_Score",
	OvertimeOptionFive_Max_Random_Team: "Five_Max_Random_Team",
}

var EnumValuesOvertimeOption = map[string]OvertimeOption{
	"Unlimited":            OvertimeOptionUnlimited,
	"Five_Max_First_Score": OvertimeOptionFive_Max_First_Score,
	"Five_Max_Random_Team": OvertimeOptionFive_Max_Random_Team,
}

func (v OvertimeOption) String() string {
	if s, ok := EnumNamesOvertimeOption[v]; ok {
		return s
	}
	return "OvertimeOption(" + strconv.FormatInt(int64(v), 10) + ")"
}
