// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type TextHAlign byte

const (
	TextHAlignLeft   TextHAlign = 0
	TextHAlignCenter TextHAlign = 1
	TextHAlignRight  TextHAlign = 2
)

var EnumNamesTextHAlign = map[TextHAlign]string{
	TextHAlignLeft:   "Left",
	TextHAlignCenter: "Center",
	TextHAlignRight:  "Right",
}

var EnumValuesTextHAlign = map[string]TextHAlign{
	"Left":   TextHAlignLeft,
	"Center": TextHAlignCenter,
	"Right":  TextHAlignRight,
}

func (v TextHAlign) String() string {
	if s, ok := EnumNamesTextHAlign[v]; ok {
		return s
	}
	return "TextHAlign(" + strconv.FormatInt(int64(v), 10) + ")"
}
